### ISSUE TITLE
libusb-0.1.so.4: cannot open shared object file

### ISSUE THREAD

**Issue by ZakCodes** [Rouji/Ergodone-Setup#1]
I followed your instructions to load the firmware but then I ran into this error while trying to reflash the firmware. I'm running arch linux if that can help. Here's my full terminal:
```
$ sudo ./reflash.sh
 _   _            _              _ _    _ _
| |_| | ____ _   | |_ ___   ___ | | | _(_) |_
| __| |/ / _` |__| __/ _ \ / _ \| | |/ / | __|
| |_|   < (_| |__| || (_) | (_) | |   <| | |_
 \__|_|\_\__, |   \__\___/ \___/|_|_|\_\_|\__|
         |___/
                                       REFLASH


Keyboard to reflash:

 Name:		ErgoDone
 MCU:		atmega32u4
 Bootloader:	hid
 Firmware:	ergodone.hex

Manipulation:

 Reflash default firmware: ../common/firmware/ergodone.hex

Do you want to continue? [Y/n] y

Reflashing hex file...
./script/../bin/hid_bootloader_cli: error while loading shared libraries: libusb-0.1.so.4: cannot open shared object file: No such file or directory
Flashing failed!

Press any key to continue . . .
```

**Comment by ZakCodes** [comment]
The problem was the version of libusb that was installed on my computer. To solve it just use this command: 
```
$sudo pacman -S libusb-compat
```
This package is necessary for running this program on arch because arch is a rolling release os. Therefore you cannot install the previous version of a package. This package was meant to solve this problem.

**Comment by Rouji** [comment]
Wasn't necessary on Tumbleweed, which is also rolling release. :)
