### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by j6s** [Rouji/Ergodone-Setup#2]
This is not a 'real' issue - I just did not find another way to thank you.

Thanks for writing this short summary.
Last time I looked at it, I concluded, that flashing from Linux is not (easily) possible.

Thanks for showing me how to flash the firmware on Linux.

**Comment by Rouji** [comment]
Thank you for the kind message! Always nice to hear my stuff's helping people.
Hope you enjoy your Ergodone!


I'm going to close this though, since, as you correctly point out, it's not really an 'issue'.
